/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:240876:
  appc.background(230);
} //_CODE_:window1:240876:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:309393:
  paused = !paused;
  if (reset == false) 
    pausedProcedure("normal");
  else 
    pausedProcedure("reset");
  
} //_CODE_:pauseButton:309393:

public void resetButtonClicked(GButton source, GEvent event) { //_CODE_:resetButton:757971:
  reset();
} //_CODE_:resetButton:757971:

public void numColoniesSliderChanged(GSlider source, GEvent event) { //_CODE_:numColoniesSlider:817304:
  paused = true;
  pausedProcedure("normal");
  numRings = numColoniesSlider.getValueI(); 
  reset = true;
} //_CODE_:numColoniesSlider:817304:

public void frameRateSliderChanged(GSlider source, GEvent event) { //_CODE_:frameRateSlider:970453:
  paused = true;
  pausedProcedure("normal"); 
  frameRate = frameRateSlider.getValueI();
  reset = true;
} //_CODE_:frameRateSlider:970453:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 320, 320, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  pauseButton = new GButton(window1, 14, 9, 80, 30);
  pauseButton.setText("Pause");
  pauseButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  pauseButton.addEventHandler(this, "pauseButtonClicked");
  resetButton = new GButton(window1, 226, 8, 80, 30);
  resetButton.setText("Reset");
  resetButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  resetButton.addEventHandler(this, "resetButtonClicked");
  numColoniesSlider = new GSlider(window1, 15, 79, 100, 40, 10.0);
  numColoniesSlider.setShowValue(true);
  numColoniesSlider.setLimits(10, 3, 20);
  numColoniesSlider.setNumberFormat(G4P.INTEGER, 0);
  numColoniesSlider.setOpaque(false);
  numColoniesSlider.addEventHandler(this, "numColoniesSliderChanged");
  label1 = new GLabel(window1, 10, 51, 126, 21);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Number of colonies");
  label1.setOpaque(false);
  frameRateSlider = new GSlider(window1, 195, 80, 100, 40, 10.0);
  frameRateSlider.setShowValue(true);
  frameRateSlider.setLimits(7, 1, 15);
  frameRateSlider.setNumberFormat(G4P.INTEGER, 0);
  frameRateSlider.setOpaque(false);
  frameRateSlider.addEventHandler(this, "frameRateSliderChanged");
  label2 = new GLabel(window1, 179, 51, 132, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Reproduction speed");
  label2.setOpaque(false);
  label3 = new GLabel(window1, 24, 138, 270, 43);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Each square-shaped ring represents an isolated colony of organisms");
  label3.setLocalColorScheme(GCScheme.RED_SCHEME);
  label3.setOpaque(true);
  label4 = new GLabel(window1, 24, 180, 270, 41);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("One cell = One organism");
  label4.setLocalColorScheme(GCScheme.RED_SCHEME);
  label4.setOpaque(true);
  label5 = new GLabel(window1, 23, 263, 269, 42);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Green = AA or Aa genotype");
  label5.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label5.setOpaque(true);
  label6 = new GLabel(window1, 23, 221, 269, 42);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Yellow = aa genotype");
  label6.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  label6.setOpaque(true);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton pauseButton; 
GButton resetButton; 
GSlider numColoniesSlider; 
GLabel label1; 
GSlider frameRateSlider; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
